### ISSUE TITLE
 setuptools is outdated error

### ISSUE THREAD

**Issue by Rubines** [resin-io-projects/boombeastic#37]
I cant install the software because I run in the setuptools is outdated error and Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-56Ct94/MechanicalSoup

A solution would be to use pip3 but no mater what I change in the Dockerfile.template it is ignored.
Iwould like to change in the apt-get portion to install python3-pip \ instead of python-pip
And then use pip3 instead of pip
Unfotunately my local changes are ignored, I don't know why I had to clone the repository when it is not used by the installer anyhow,....

This is super frustrating and I have no idea how to solve this issue.

Please help

**Comment by curcuz** [comment]
@rubines first of all, are you committing your local changes before pushing to resin? Secondly, Master is indeed broken atm due to breaking changes introduced recently by Mopidy. You can push the 1.0.0-beta1 branch in the meantime and have airplay and spotify connect functionalities on your boombeastic with `git checkout 1.0.0-beta1 && git push resin 1.0.0-beta1:master
